CREATE TABLE `auths` (
	`id` int AUTO_INCREMENT NOT NULL,
	`username` varchar(255) NOT NULL,
	`password` varchar(255) NOT NULL,
	`profilePublicId` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`country` varchar(255) NOT NULL,
	`profilePicture` varchar(255) NOT NULL,
	`emailVerificationToken` varchar(255) NOT NULL,
	`emailVerified` boolean NOT NULL DEFAULT false,
	`browserName` varchar(255) NOT NULL,
	`deviceType` varchar(255) NOT NULL,
	`otp` varchar(255),
	`otpExpiration` date,
	`createdAt` timestamp DEFAULT (now()),
	`passwordResetToken` varchar(255),
	`passwordResetExpires` timestamp,
	CONSTRAINT `auths_id` PRIMARY KEY(`id`),
	CONSTRAINT `idIndex` UNIQUE(`id`),
	CONSTRAINT `emailIndex` UNIQUE(`email`),
	CONSTRAINT `userNameIndex` UNIQUE(`username`),
	CONSTRAINT `emailVerificationTokenIndex` UNIQUE(`emailVerificationToken`)
);
